package by.academy.final_project.entities;

public enum FilmsGenre {

    SHORT_FILM, ACTION, ADVENTURE, COMEDY, DRAMA, CRIME, HORROR, FANTASY, ROMANCE, THRILLER, ANIMATION, FAMILY, WAR,
    DOCUMENTARY, MUSICAL, BIOGRAPHY, SCI_FI, WESTERN, POST_APOCALYPTIC

}
